version: "3.7"

services:
  simple-nodejs-proxy:
    build:
      context: .
      dockerfile: Dockerfile
#      dockerfile: Dockerfile.development
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'


